name = "yalla-masry-academy-1"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[vars]
# ğŸ‘‘ Ù‡Ù†Ø§ Ù†Ø¶Ø¹ Ø§Ù„Ù…ÙØªØ§Ø­ Ø§Ù„Ø°ÙŠ ÙƒØ§Ù† ÙŠØ³Ø¨Ø¨ Ø§Ù„Ø£Ø²Ù…Ø© Ù„Ø¶Ù…Ø§Ù† Ø±Ø¤ÙŠØªÙ‡ ÙˆÙ‚Øª Ø§Ù„Ø¨Ù†Ø§Ø¡
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "yalla-masry-academy"

[[routes]]
pattern = "/*"
script = "_worker.js"
